version: '3.8'

services:
  db:
    image: mariadb:lts
    container_name: nextcloud_db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    networks:
      - nextcloud
     

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    networks:
      - nextcloud
     
      

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./data:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
    environment:
      - MYSQL_PASSWORD=nextcloudpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=adminpass
      - TRUSTED_PROXIES=reverse_proxy
      - OVERWRITEPROTOCOL=http
      
    ports:
      - "8082:80"   # ← C’est cette ligne qu’il faut ajouter
      
    networks:
      - nextcloud

  

networks:
  nextcloud:
