version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=nextcloudpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
    volumes:
      - ./data/db:/var/lib/mysql

  app:
    image: nextcloud
    restart: always
    container_name: nextcloud_app
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=nextcloudpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_HOST=db
    volumes:
      - ./data/nextcloud:/var/www/html
